- name: Metrics embed
  uses: lowlighter/metrics@v3.29

  with:
    filename: workflows/metrics.plugin.isocalendar.fullyear.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_isocalendar: yes
    plugin_isocalendar_duration: full-year
